; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Wed May 26 2021 22:02:28 GMT-0600 (Mountain Daylight Time)
M280 P0 S10 ; deploy BLTouch

