; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Wed May 26 2021 22:02:30 GMT-0600 (Mountain Daylight Time)
; Wait for set temperatures to be reached
M116 P0

